---
- name: 'Instalar PHP'
  apt:
    name: "{{ item }}"       
    state: latest
  become: yes
  with_items:
    - php7.1
    - apache2
    - libapache2-mod-php7.1
    - php7.1-gd
    - php7.1-ssh2
    - php7.1-mcrypt
    - php7.1-mysql  