- name: 'Baixa o arquivo de instalacao do Wordpress'
  get_url: 
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompacta o Wordpress'
  unarchive: 
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: 'Copia o arquivo do php do wordpress'
  copy:
    src: '{{ wp_path }}/wp-config-sample.php'
    dest: "{{ wp_path }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura o wp-config com as entradas do banco de dados'
  replace:
    path: "{{ wp_path }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
  - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
  - { regex: 'username_here', value: "{{ wp_db_user }}" }
  - { regex: 'password_here', value: "{{ wp_db_pass }}" }
  - { regex: 'localhost', value: "{{ wp_db_host }}"}
  become: yes

- name: 'Configura Apache para servir Wordpress'
  template:
    src: 'roles/templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache